### ISSUE TITLE
Questions about creating environment based on conda

### ISSUE THREAD

**Issue by HelloWorldLTY** [jranek/delve_benchmark#1]
Hi, based on the uploaded file, I cannot install the conda envrionment:

Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining anndata2ri[version='>=1.0.6']:  35%|██████████████▌                           | 9/26 [00:40<01:30,  5.35s/it]\Examining anndata[version='>=0.7.6']:  58%|█████████████████████████▍                  | 15/26 [01:03<00:58,  5.28s/it]-Examining numpy==1.22.4:  62%|███████████████████████████████████                      | 16/26 [01:06<00:47,  4.75s/it]-Examining pandas[version='>=1.1.5']:  77%|██████████████████████████████████▌          | 20/26 [01:12<00:17,  2.89s/it]-Examining tqdm:  92%|████████████████████████████████████████████████████████████▉     | 24/26 [01:57<00:13,  6.97s/it]-Examining scikit-learn==0.23.2:  92%|██████████████████████████████████████████████▏   | 24/26 [02:02<00:13,  6.97s/it]\Examining conflict for seaborn scprep phate scikit-learn statsmodels networkx umap-learn scanpy numba matplotlib-venn p\Examining conflict for seaborn scprep statsmodels networkx scanpy pandas anndata:  73%|▋| 19/26 [03:13<01:27, 12.54s/it-Examining conflict for scprep phate scikit-learn statsmodels networkx umap-learn scanpy matplotlib-venn scipy anndata: \Examining conflict for seaborn python scprep phate statsmodels anndata2ri networkx scanpy pip matplotlib-venn pandas ma\
Examining conflict for statsmodels python-igraph pip seaborn python scprep anndata2ri numba scipy anndata numpy phate neExamining conflict for numpy python statsmodels python-igraph pandas matplotlib-base scipy: : 27it [04:54, 10.63s/it]   Examining conflict for matplotlib-inline scprep statsmodels scanpy pip pandas matplotlib-base scipy anndata: : 28it [05:Examining conflict for matplotlib-inline scprep statsmodels scanpy pip pandas matplotlib-base scipy anndata: : 29it [05:Examining conflict for scprep phate scikit-learn python-igraph matplotlib-venn pandas scipy: : 29it [05:18, 12.14s/it]  Examining conflict for numpy scprep phate scikit-learn python-igraph matplotlib-venn pandas r-base scipy: : 31it [05:35,Examining conflict for numpy scprep phate scikit-learn python-igraph matplotlib-venn pandas r-base scipy: : 32it [05:35,Examining conflict for python-igraph umap-learn scanpy numba scipy: : 32it [05:46, 10.30s/it]
Examining conflict for seaborn phate networkx numba umap-learn scanpy pip matplotlib-venn pandas matplotlib-base: : 35itExamining conflict for anndata2ri umap-learn scanpy numba anndata: : 36it [06:10,  8.75s/it]
failed
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining python[version='>=3.6']:  31%|██████████████▊                                 | 8/26 [00:33<01:32,  5.16s/it]/
Examining anndata[version='>=0.7.6']:  58%|█████████████████████████▍                  | 15/26 [01:04<00:59,  5.43s/it]|
Examining numpy==1.22.4:  62%|███████████████████████████████████                      | 16/26 [01:07<00:48,  4.86s/it]|
Examining networkx[version='>=2.5.1']:  69%|█████████████████████████████▊             | 18/26 [01:09<00:26,  3.32s/it]/
Examining r-base=4.1.1:  81%|██████████████████████████████████████████████▊           | 21/26 [01:58<00:29,  

Such erros are caused by package conflicts. Could you please help me address it? Thanks.

**Comment by jranek** [comment]
Hi @HelloWorldLTY , thank you for checking out the repo! Absolutely, could you provide we with a little more information regarding what you'd like to use it for (delve feature selection, feature selection in general, simulation and feature selection), as well as details regarding your OS (windows, linux distro, mac intel, mac m)?

**Comment by HelloWorldLTY** [comment]
It is on windows. It seems that this is a problem in some yml files:

https://stackoverflow.com/questions/58216917/create-conda-environment-found-conflicts-when-solving-environment-and-findi
